name: Code Quality Analysis

on: [push]

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gitpython
        npm install -g eslint
    
    - name: Run analysis
      run: |
        python scripts/gitAnalysis.py
        python scripts/codeQualityAnalysis.py
